### ISSUE TITLE
Does it also support linux?

### ISSUE THREAD

**Issue by squirrelfeng** [devel0/netcore-opengl#1]
Great! is it possible to port to linux?
Currently still not find an opengl control for avalonia to use in linux, seems opentk also have no context.

**Comment by devel0** [comment]
I was developed and tested under linux and it could run without modification either within windows thanks for silk net.

Give a try from linux, clone the repo, or if already done start a `git pull` due to a [recent commit](https://github.com/devel0/netcore-opengl/commit/5a7fde43360408fad7407f1e1f20c2606d8b683d) required to upgrade at net6 then issue a `dotnet run --project examples/0003` and you should be able to start the example project.
